### ISSUE TITLE
README badges point to 2020 repository

### ISSUE THREAD

**Issue by mifrandir** [Hyp-ed/hyped-2021#22]
The current badges, i.e.

[![Build Status](https://travis-ci.org/Hyp-ed/hyped-2020.svg?branch=develop)](https://travis-ci.org/Hyp-ed/hyped-2020)
[![Coverage Status](https://codecov.io/gh/hyp-ed/hyped-2020/branch/develop/graph/badge.svg)](https://codecov.io/gh/hyp-ed/hyped-2020)

refer to the [hyped-2020](https://github.com/Hyp-ed/hyped-2020) repository. This makes them basically useless and, worse than that, misleading.

I have considered removing them and submitting a PR but I am not sure this is the way to go. I would rather have it fixed because these tools are convenient. We should probably use GitHub actions though as to avoid having to set up TravisCI every year.

What do you think?

@DonaldJennings @MeinaLinWei

**Comment by DonaldJennings** [comment]
QA have had a discussion earlier this year about setting up Travis again and it completely slipped our mind . We were intending to do this last semester. I am not really familiar with GitHub actions or Travis but intuition tells me that GitHub actions is probably a lot more maintainable for not setting it up every year. I'll start looking into this :)

**Comment by mifrandir** [comment]
Alright :) 

If you need any help, let me know. I've worked with GitHub Actions before.
It shouldn't be more complicated than setting up two jobs, one with
```
$ make
```
and one with 
```
$ make test
```

**Comment by DonaldJennings** [comment]
Yeah some help would be great :) . I'll discuss it with Pablo and the team tomorrow :)
